BASE_TASK_CONFIG_PATH: run_R2RIE-CE/r2r_vlnce.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
TORCH_GPU_IDS: [0]
TRAINER_NAME: SS-BEV
GPU_NUMBERS: 1
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/results/tensorboard_dirs/
CHECKPOINT_FOLDER: data/results/checkpoints/ #  "data/logs/ckpt_debug",
EVAL_CKPT_PATH_DIR: data/results/checkpoints/
RESULTS_DIR: data/results/logs/eval_results/

VIDEO_DIR: data/logs/video/
VIDEO_OPTION: [] # disk

INFERENCE:
  SPLIT: test
  USE_CKPT_CONFIG: False
  SAMPLE: False
  CKPT_PATH: '' # REPLACE THIS
  PREDICTIONS_FILE: ''
  FORMAT: r2r
  EPISODE_COUNT: -1

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT:  val_unseen_wrong_dataset_both 
  EPISODE_COUNT: -1
  CKPT_PATH_DIR: ''
  fast_eval: False

IL:
  iters: 15000
  log_every: 200
  lr: 1e-5
  batch_size: 1 # equal to NUM_ENVIRONMENTS
  ml_weight: 1.0
  expert_policy: spl

  sample_ratio: 0.75
  decay_interval: 3000
  
  max_traj_len: 15
  max_text_len: 80
  loc_noise: 0.5
  waypoint_aug: False
  ghost_aug: 0.0
  back_algo: teleport
  tryout: True

MODEL:
  task_type: r2r

  policy_name: PolicyViewSelectionBEV
  NUM_ANGLES: 12
  pretrained_path: null
  fix_lang_embedding: False
  fix_pano_embedding: False
  use_depth_embedding: True
  use_sprels: True
  merge_ghost: True
  consume_ghost: True
  
  spatial_output: False
  RGB_ENCODER:
    output_size: 512
  DEPTH_ENCODER:
    output_size: 256    
  VISUAL_DIM:
    vis_hidden: 768
    directional: 128
  INSTRUCTION_ENCODER:
    bidirectional: True

